agent:
  alpha: 0.1
  batch_size: 64
  buffer_size: 100000
  double_dqn: false
  dueling_dqn: false
  epsilon_decay: 0.995
  epsilon_min: 0.01
  epsilon_start: 1.0
  gamma: 0.95
  hidden_dim: 128
  lr: 6.90767e-05
  name: dqn
environment:
  arrival_rates:
    E_to_N: 0.05
    E_to_S: 0.05
    E_to_W: 0.15
    N_to_E: 0.05
    N_to_S: 0.15
    N_to_W: 0.05
    S_to_E: 0.05
    S_to_N: 0.15
    S_to_W: 0.05
    W_to_E: 0.15
    W_to_N: 0.05
    W_to_S: 0.05
  max_steps: 1000
  traffic_multiplier: 1.0
train:
  device: cuda
  eval_freq: 50
  n_episodes: 1000
  seed: 42
